<a href="https://colab.research.google.com/github/Anshii2710/Anshii2710/blob/main/RNNs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [ ]:
model=Sequential()

model.add(SimpleRNN(3,input_shape=(4,5))) #adding layers with 3 neurons getting input of max temesteps=4 and vocab=5
model.add(Dense(1,activation='sigmoid'))#one neuron for binary classification

model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_14 (SimpleRNN)       │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()[0].shape #input and hidden layer weight matrix


(5, 3)

In [ ]:
print(model.get_weights()[1])
model.get_weights()[1].shape #hidden connections weight matrix


[[-0.08035314  0.8548664   0.5125885 ]
 [-0.9905312  -0.12591332  0.05471623]
 [-0.11131682  0.5033383  -0.85688925]]


(3, 3)

Integer Encoding in Sentiment Analysis

In [ ]:
import numpy as np

docs=['go india',
      'india india',
      'hip hip hurray',
      'kohli kohli']  #we have data and now we have to vectorize it

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')#initializing tokenizer which is used to tokenize words
#oov is used to assign nothing to all words which are not in the vocab

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_index

{'<nothing>': 1, 'india': 2, 'hip': 3, 'kohli': 4, 'go': 5, 'hurray': 6}

In [ ]:
tokenizer.word_counts #this counts the frequency of words in the docu

OrderedDict([('go', 1), ('india', 3), ('hip', 2), ('hurray', 1), ('kohli', 2)])

In [ ]:
tokenizer.document_count #no of sentences or inputs in the doc i.e rows

4

In [ ]:
sequences=tokenizer.texts_to_sequences(docs)
sequences #these are of different sizes hence we need to apply zero padding

[[5, 2], [2, 2], [3, 3, 6], [4, 4]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences=pad_sequences(sequences,padding='post')#post means zero to be included at last
sequences

array([[5, 2, 0],
       [2, 2, 0],
       [3, 3, 6],
       [4, 4, 0]], dtype=int32)

Sentiment Analysis using IMDB Dataset

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

# Load IMDB data, limiting the vocabulary size to 10000
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=10000)

In [ ]:
X_train #the data is already tokenized(Integer Encoded) i.e preprocessed

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [ ]:
X_train[0] #represents one review
#the problem is these are not of same length and hence we need zero padding

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [ ]:
X_train=pad_sequences(X_train,padding='post',maxlen=50) #every senetence is trimmed to be of 50 length only
X_test=pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
model=Sequential()
#for every word we have one integer and maximum timesteps are 50 in one input becuase maxlen=50
#return sequences=False means output of each word is not passed out t
model.add(Embedding(10000,output_dim=2,input_length=50)) #so vocab is 10000 so every intger encoded word is passed as one hot encoding internally
model.add(SimpleRNN(32,return_sequences=False)) #hidden layer of 32 neurons
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_15 (SimpleRNN)       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 20ms/step - accuracy: 0.5650 - loss: 0.6618 - val_accuracy: 0.7961 - val_loss: 0.4394
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.8322 - loss: 0.3855 - val_accuracy: 0.8044 - val_loss: 0.4285
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 16ms/step - accuracy: 0.8725 - loss: 0.3121 - val_accuracy: 0.8070 - val_loss: 0.4429
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.8950 - loss: 0.2711 - val_accuracy: 0.8002 - val_loss: 0.4602
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.9112 - loss: 0.2365 - val_accuracy: 0.7979 - val_loss: 0.4991
